# 鍵盤配置
Keyboard=Dubeolsik
# 自動排序
AutoReorder=True
# 組合雙輔音
CombiOnDoubleStroke=False
# 組合非詞首輔音
NonChoseongCombi=True
# 單字提交
WordCommit=False
# 漢字模式
HanjaMode=False

[HanjaModeToggleKey]
0=Hangul_Hanja
1=F9

[PrevPage]
0=Up

[NextPage]
0=Down

[PrevCandidate]
0=Shift+Tab

[NextCandidate]
0=Tab

