[Table]
# 選擇第二個候選詞
SecondCandidate=
# 選擇第三個候選詞
ThirdCandidate=
# 每頁候選字詞
PageSize=9
# 自動選擇候選詞後提交
CommitAfterSelect=True
# 在取消激活輸入法時提交輸入緩衝區
CommitWhenDeactivate=True
# 提交無效段
CommitInvalidSegment=False
# 使用全形字元
UseFullWidth=True
# 忽略內建標點
IgnorePunc=False
# 將第一個候選詞作為預編輯文字
FirstCandidateAsPreedit=False
# 將內嵌預編輯游標位置固定在預編輯的開頭
PreeditCursorPositionAtBeginning=True
# 快速輸入的觸發按鍵
QuickPhraseKey=
# 觸發快速輸入的文本
QuickPhraseText=
# 不對短於...的詞排序
NoSortInputLength=0
# 按碼長排序候選詞
SortByCodeLength=True
# 排序規則
OrderPolicy=Freq
# 使用系統語言模型
UseSystemLanguageModel=True
# 依據上下文排序候選詞
UseContextRelatedOrder=True
# 模糊鍵
MatchingKey=asterisk
# 觸發拼音的前綴鍵
PinyinKey=grave
# 自動選擇候選字
AutoSelect=True
# 選擇唯一候選詞的長度限制
AutoSelectLength=-1
# 選擇唯一候選詞的正則表達式
AutoSelectRegex=
# 沒有匹配時自動選擇
NoMatchAutoSelectLength=0
# 沒有匹配時用於自動選擇的正則表達式
NoMatchAutoSelectRegex=
# 自動片語長度
AutoPhraseLength=-1
# 詞組參與自組詞
AutoPhraseWithPhrase=False
# 候選詞中自動組詞的標記符號
MarkerForAutoPhrase=*
# 在輸入...次後儲存自動組詞
SaveAutoPhraseAfter=-1
# 精確匹配
ExactMatch=False
# 學習
Learning=False
# 顯示單字提示
Hint=False
# 顯示自訂提示
DisplayCustomHint=True
# 提示與候選詞之間的分隔符文本
HintSeparator=" ~ "
# 候選詞清單配置
CandidateLayoutHint=Horizontal
# 允許使用數字鍵盤輸入字碼
KeypadAsInput=False

[Table/PrevPage]
0=Up
1=minus

[Table/NextPage]
0=Down
1=equal

[Table/PrevCandidate]
0=Left

[Table/NextCandidate]
0=Right

[Table/DefaultCandidate]
0=space

